name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Run vcpkg
      uses: lukka/run-vcpkg@v10.7
      with:
        vcpkgGitCommitId: 8daf70c56ba9581f5251a5d4675eb771b6b34957
        vcpkgArguments: 'boost:${{matrix.triplet}} nlohmann-json:${{matrix.triplet}} curl:${{matrix.triplet}} libproxy:${{matrix.triplet}}'
        vcpkgDirectory: '${{github.workspace}}/vcpkg'
    - name: Run cmake(Build Release)
      uses: lukka/run-cmake@v10.3
      with:
        cmakeListsTxtPath: '${{github.workspace}}/CMakeLists.txt'
        configurePreset: 'ninja-multi-vcpkg'
        buildPreset: 'ninja-multi-vcpkg'
        buildPresetAdditionalArgs: '[`--config Release`]'
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
    - name: Upload build artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        path: ${{github.workspace}}/build/*.tar.gz
        name: artifact_${{matrix.os}}_${{matrix.configs}}.tar.gz
